spring:
  datasource:
      url: jdbc:mysql://localhost:3306/cx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: wdWJH520...
mybatis:
  mapperLocations: classpath:/mapper/*.xml
logging:
  config: classpath:logback-local.xml
